name: prolog_teste
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-198.0.dev

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.4
  flutter_triple: 2.0.1
  google_fonts: ^6.2.1
  triple: 2.1.0
  http: ^1.3.0
  intl: ^0.19.0
  mocktail: ^0.3.0
  triple_test: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
